import {
  createSlice,
  CreateSliceOptions,
  PayloadAction,
  Slice,
  SliceCaseReducers,
  SliceSelectors
} from '@reduxjs/toolkit';
import { Builder } from './extraReducersBuilder';
import { listenerMiddleware } from './middleware';
import Settings from './settings';
import { RehydrateActionPayload } from './types';
import UpdatedAtHelper from './updatedAtHelper';
import { REHYDRATE, writePersistedStorage } from './utils';

/**
 * A wrapper around the standard RTK `createSlice()` function that adds
 * persistence capabilities.
 *
 * The state will be persisted across multiple application reloads.
 * This function requires the use of {@link configurePersistedStore}.
 *
 * @param sliceOptions - The standard `CreateSliceOptions` object from Redux Toolkit.
 * @returns A Redux slice object with persistence enabled.
 *
 * @public
 */
export const createPersistedSlice: <
  SliceState,
  Name extends string = string,
  PCR extends
    SliceCaseReducers<SliceState> = SliceCaseReducers<SliceState>,
  ReducerPath extends string = Name,
  PeristedSelectors extends
    SliceSelectors<SliceState> = SliceSelectors<SliceState>,
>(
  sliceOptions: CreateSliceOptions<
    SliceState,
    PCR,
    Name,
    ReducerPath,
    PeristedSelectors
  >,
) => Slice<SliceState, PCR, Name, ReducerPath, PeristedSelectors> = <
  SliceState,
  Name extends string = string,
  PCR extends
    SliceCaseReducers<SliceState> = SliceCaseReducers<SliceState>,
  ReducerPath extends string = Name,
  PeristedSelectors extends
    SliceSelectors<SliceState> = SliceSelectors<SliceState>,
>(
  sliceOptions: CreateSliceOptions<
    SliceState,
    PCR,
    Name,
    ReducerPath,
    PeristedSelectors
  >,
) => {
  /**
   * Registers the slice's name to the list of persisted slices.
   * This allows the persistence logic to identify which parts of the state to manage.
   */
  Settings.subscribeSlice(sliceOptions.name);

  /**
   * A timeout variable to manage the debouncing of the storage write.
   * @internal
   */
  let debounceTimeout: NodeJS.Timeout | null = null;

  /**
   * Debounces the `writePersistedStorage` function to prevent excessive writes
   * during rapid state changes. The state is saved 100ms after the last change.
   * @param state - The current root state of the Redux store.
   * @param name - The name of the slice to persist.
   * @internal
   */
  const onDump = (state: Record<Name, SliceState>, name: Name) => {
    if (debounceTimeout) clearTimeout(debounceTimeout);
    debounceTimeout = setTimeout(() => {
      writePersistedStorage(state, name);
    }, 100);
  };

  /**
   * Creates a typed instance of the listener middleware's startListening function.
   * @internal
   */
  const startAppListening =
    listenerMiddleware.startListening.withTypes<
      Record<Name, SliceState>
    >();

  /**
   * Creates the slice using the default options passed by the user,
   * enhancing it with persistence logic.
   * @internal
   */
  const slice = createSlice({
    ...sliceOptions,
    extraReducers: builder => {
      const b = new Builder(builder, UpdatedAtHelper.onStateChange.bind(null, sliceOptions.name));
      // Add a case to handle the rehydration of state from storage.
      b.builder.addCase(REHYDRATE.toString(), (_state, action: PayloadAction<RehydrateActionPayload<Name, SliceState>>): void | SliceState => {
        if (action.payload?.[sliceOptions.name]) return action.payload[sliceOptions.name];
      });
      // Allow the user to add their own extra reducers.
      sliceOptions.extraReducers?.(b);
    },
  });

  /**
   * Listens for each action generated by the slice to trigger persistence
   * immediately after the state is updated by its own reducers.
   * @internal
   */
  Object.keys(slice.actions).forEach(type => {
    startAppListening({
      type: `${slice.name}/${type}`,
      effect: (_action, { getState }) => {
        const state = getState();
        onDump(state, sliceOptions.name);
      },
    });
  });

  /**
   * Listens for any other action to check if the state managed by this slice
   * has been updated by an extra reducer and needs to be persisted.
   * @internal
   */
  startAppListening({
    predicate: (action) => {
      // Exclude the slice's own actions (already handled) and the rehydrate action.
      if (action.type === REHYDRATE.toString() || action.type.startsWith(`${slice.name}/`)) return false;
      return true;
    },
    effect: async (_action, { getState }) => {
      if (!await UpdatedAtHelper.shouldSave(sliceOptions.name)) return;
      const state = getState();
      onDump(state, sliceOptions.name);
    },
  });

  /**
   * Listens for the rehydration action to update the local timestamp and
   * set the `isHydrated` flag to prevent subsequent rehydrations.
   * @internal
   */
  startAppListening({
    actionCreator: REHYDRATE,
    effect: () => {
      UpdatedAtHelper.onStateChange(sliceOptions.name);
    },
  });

  return slice;
};
