import {
  createSlice,
  CreateSliceOptions,
  PayloadAction,
  SliceCaseReducers,
  SliceSelectors
} from '@reduxjs/toolkit';
import { Builder } from './extraReducersBuilder';
import { listenerMiddleware } from './middleware';
import Settings from './settings';
import { NestedPath, PersistedSlice, RehydrateActionPayload } from './types';
import UpdatedAtHelper from './updatedAtHelper';
import { deepGetByPath, REHYDRATE, writePersistedStorage } from './utils';

/**
 * A wrapper around the standard RTK `createSlice()` function that adds
 * persistence capabilities.
 *
 * The state will be persisted across multiple application reloads.
 * This function requires the use of {@link configurePersistedStore}.
 *
 * @param sliceOptions - The standard `CreateSliceOptions` object from Redux Toolkit.
 * @param nesting - An optional dot-separated string path indicating where the slice is nested within the root state.
 * @returns A Redux slice object with persistence enabled, enhanced with a `nestedPath` property that has a correctly inferred literal type.
 *
 * @public
 */
export const createPersistedSlice = <
  SliceState,
  Name extends string,
  PCR extends SliceCaseReducers<SliceState>,
  ReducerPath extends string = Name,
  PeristedSelectors extends SliceSelectors<SliceState> = SliceSelectors<SliceState>,
  Nesting extends string | undefined = undefined
>(
  sliceOptions: CreateSliceOptions<
    SliceState,
    PCR,
    Name,
    ReducerPath,
    PeristedSelectors
  >,
  nesting?: Nesting,
): PersistedSlice<SliceState, PCR, Name, ReducerPath, PeristedSelectors, Nesting> => {
  /**
   * Registers the slice's name to the list of persisted slices.
   * This allows the persistence logic to identify which parts of the state to manage.
   */
  Settings.subscribeSlice(sliceOptions.name);

  const name = sliceOptions.reducerPath ?? sliceOptions.name;
  /**
   * The full dot-separated path to the slice's state within the root state object.
   * @internal
   */
  const nestedPath = (nesting && nesting !== '' ? `${nesting}.${name}` : name) as NestedPath<ReducerPath, Nesting>;

  /**
   * A timeout variable to manage the debouncing of the storage write.
   * @internal
   */
  let debounceTimeout: NodeJS.Timeout | null = null;

  /**
   * Debounces the `writePersistedStorage` function to prevent excessive writes
   * during rapid state changes. The state is saved 100ms after the last change.
   * @param state - The current root state of the Redux store.
   * @internal
   */
  const onDump = (state: Record<string, any>) => {
    if (debounceTimeout) clearTimeout(debounceTimeout);
    debounceTimeout = setTimeout(() => {
      // Use deepGetByPath with the single correct path
      const sliceState = deepGetByPath(state, nestedPath);
      writePersistedStorage(sliceState, sliceOptions.name);
    }, 100);
  };

  /**
   * Creates a typed instance of the listener middleware's startListening function.
   * @internal
   */
  const startAppListening =
    listenerMiddleware.startListening.withTypes<Record<string, any>>();

  /**
   * Creates the slice using the default options passed by the user,
   * enhancing it with persistence logic.
   * @internal
   */
  const slice = createSlice({
    ...sliceOptions,
    extraReducers: builder => {
      // Add a case to handle the rehydration of state from storage.
      builder.addCase(REHYDRATE.toString(), (_state, action: PayloadAction<RehydrateActionPayload<Name, SliceState>>): void | SliceState => {
        if (action.payload?.[sliceOptions.name]) return action.payload[sliceOptions.name];
      });
      const b = new Builder(builder, UpdatedAtHelper.onStateChange.bind(null, sliceOptions.name));
      // Allow the user to add their own extra reducers.
      sliceOptions.extraReducers?.(b);
    },
  });

  /**
   * Listens for each action generated by the slice to trigger persistence
   * immediately after the state is updated by its own reducers.
   * @internal
   */
  Object.keys(slice.actions).forEach(type => {
    startAppListening({
      type: `${slice.name}/${type}`,
      effect: (_action, { getState }) => {
        const state = getState();
        onDump(state);
      },
    });
  });

  /**
   * Listens for any other action to check if the state managed by this slice
   * has been updated by an extra reducer and needs to be persisted.
   * @internal
   */
  startAppListening({
    predicate: (action) => {
      // Exclude the slice's own actions (already handled) and the rehydrate action.
      if (action.type === REHYDRATE.toString() || action.type.startsWith(`${slice.name}/`)) return false;
      return true;
    },
    effect: async (_action, { getState }) => {
      if (!await UpdatedAtHelper.shouldSave(sliceOptions.name)) return;
      const state = getState();
      onDump(state);
    },
  });

  /**
   * Listens for the rehydration action to update the local timestamp
   * @internal
   */
  startAppListening({
    actionCreator: REHYDRATE,
    effect: () => UpdatedAtHelper.onSave(sliceOptions.name),
  });

  return { ...slice, nestedPath };
};
